name: Coverage report

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  coverage:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' }}

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_commit.id }}
      - name: Download Coverage Artifacts
        uses: actions/download-artifact@v4.3.0
        with:
          name: coverage
          path: coverage
      - name: Produce Coverage report
        uses: ./
        with:
          path: coverage/cobertura-coverage.xml
          minimum_coverage: 75
          fail_below_threshold: true
